### PR TITLE
Bump version to 3.0.0.rc1

### PR DESCRIPTION
**Pull request by vsppedro**
### Backward-incompatible changes

* Drop support for Ruby 2.5 and 2.6 by @vsppedro. Ruby 2.7.x is the only version supported now. ([#76], [#77], [#78])
* Drop support for Rails 4.2, 5.0, 5.1 and 5.2 by @vsppedro. Rails 6.0.x and Rails 6.1.x are the only versions supported now. ([#79], [#80], [#81], [#82])

[#74]: https://github.com/thoughtbot/shoulda-context/pull/74
[#76]: https://github.com/thoughtbot/shoulda-context/pull/76
[#77]: https://github.com/thoughtbot/shoulda-context/pull/77
[#78]: https://github.com/thoughtbot/shoulda-context/pull/78
[#79]: https://github.com/thoughtbot/shoulda-context/pull/79
[#80]: https://github.com/thoughtbot/shoulda-context/pull/80
[#81]: https://github.com/thoughtbot/shoulda-context/pull/81
[#82]: https://github.com/thoughtbot/shoulda-context/pull/82

### Bug fixes

* Fix broken thoughtbot logo on README.md by @sarahraqueld. ([#0551d18c92eebd94db70917d668202508b7d2268])
* Use proper source location for should calls without a block by @segiddins. ([#92])
* Fix the link to the gem on Rubygems in the README by @mcmire and @0xRichardH. ([#1098f5beb9b49a9d88434f6b3b6ccb58b2dfe93f])
* Fix a method redefinition warning by @Earlopain. ([#94])

[#0551d18c92eebd94db70917d668202508b7d2268]: https://github.com/thoughtbot/shoulda-context/commit/0551d18c92eebd94db70917d668202508b7d2268
[#92]: https://github.com/thoughtbot/shoulda-context/pull/92
[#94]: https://github.com/thoughtbot/shoulda-context/pull/94

### Features

* Add support for Rails 6.1 by @vsppedro. ([#84])

[#84]: https://github.com/thoughtbot/shoulda-context/pull/84

### Improvements

* Update README for consistency across all shoulda-* gems by @mcmire. ([#5da1895f6c9917bc2aa0a248c209edb453a1340e])
* Bump warnings_logger to 0.1.1 by @mcmire. ([#970d3d57a584ecb2652f0bc7188761024de16c52])
* Add 'Getting started' section to the README by @mcmire. ([#52915f3a3cb36ae0494cfbacccc162b95932ca24])
* Switch to Github Actions by @vsppedro. ([#74], [#83])
* Do fewer intermediary allocations when calculating test methods by @segiddins. ([#89])
* Call dynamic-readme reusable workflow by @stefannibrasil. ([#95])

[#5da1895f6c9917bc2aa0a248c209edb453a1340e]: https://github.com/thoughtbot/shoulda-context/commit/5da1895f6c9917bc2aa0a248c209edb453a1340e
[#970d3d57a584ecb2652f0bc7188761024de16c52]: https://github.com/thoughtbot/shoulda-context/commit/970d3d57a584ecb2652f0bc7188761024de16c52
[#52915f3a3cb36ae0494cfbacccc162b95932ca24]: https://github.com/thoughtbot/shoulda-context/commit/52915f3a3cb36ae0494cfbacccc162b95932ca24
[#1098f5beb9b49a9d88434f6b3b6ccb58b2dfe93f]: https://github.com/thoughtbot/shoulda-context/commit/1098f5beb9b49a9d88434f6b3b6ccb58b2dfe93f
[#83]: https://github.com/thoughtbot/shoulda-context/pull/83
[#89]: https://github.com/thoughtbot/shoulda-context/pull/89
[#95]: https://github.com/thoughtbot/shoulda-context/pull/95

### CODE REVIEW

**Comment by Earlopain** [comment]
Hey, I wanted to give this one a try but I don't see a release yet. Am I too early?

**Comment by vsppedro** [comment]
Sorry for that. I'm currently encountering an issue with the command responsible for creating the release. I'll make another attempt today. Thank you for your patience.

**Comment by vsppedro** [comment]
Unfortunately, I don't have the right permissions to make a new version.

**Comment by matsales28** [comment]
> Hey, @matsales28, sorry to bother you with this, but I'm not sure who to ask. Do you know anyone who could help with releasing an update for this gem, please?

@vsppedro, I just added you to the list of owners in RubyGems. I tried to make the release myself, but some errors were happening in the bundle, so I stopped. Feel free to ping me if you need something else.

**Comment by vsppedro** [comment]
@matsales28, thank you! It worked.

**Pull request merged**
