### PR TITLE
Uses class_eval when dynamically creating tests so that we can pass in source location

### PR DESCRIPTION
**Pull request by alexpjohnson**
For #50

### CODE REVIEW

**Comment by michaldarda** [comment]
@alexpjohnson @jferris any chance for this to be merged in?

**Comment by alexpjohnson** [comment]
I'd be happy to, but I don't have write access. We would need someone from thoughtbot to take a look.

**Comment by alexpjohnson** [comment]
@travisjeffery Would you mind taking a look at this?

**Comment by travisjeffery** [comment]
Thanks for bringing this up again! Just released 1.2.2 for this

**Pull request merged**
